//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace OfficeDevPnP.PartnerPack.Infrastructure.Configuration {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration", IsNullable=false)]
    public partial class PnPPartnerPackConfiguration {
        
        private PnPPartnerPackConfigurationTenantSettings tenantSettingsField;
        
        private DotNetHandlerType provisioningRepositoryField;
        
        private PnPPartnerPackConfigurationJobHandler[] jobsHandlersField;
        
        /// <remarks/>
        public PnPPartnerPackConfigurationTenantSettings TenantSettings {
            get {
                return this.tenantSettingsField;
            }
            set {
                this.tenantSettingsField = value;
            }
        }
        
        /// <remarks/>
        public DotNetHandlerType ProvisioningRepository {
            get {
                return this.provisioningRepositoryField;
            }
            set {
                this.provisioningRepositoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("JobHandler", IsNullable=false)]
        public PnPPartnerPackConfigurationJobHandler[] JobsHandlers {
            get {
                return this.jobsHandlersField;
            }
            set {
                this.jobsHandlersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
    public partial class PnPPartnerPackConfigurationTenantSettings {
        
        private string tenantField;
        
        private string infrastructureSiteUrlField;
        
        private string appOnlyCertificateThumbprintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tenant {
            get {
                return this.tenantField;
            }
            set {
                this.tenantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string infrastructureSiteUrl {
            get {
                return this.infrastructureSiteUrlField;
            }
            set {
                this.infrastructureSiteUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appOnlyCertificateThumbprint {
            get {
                return this.appOnlyCertificateThumbprintField;
            }
            set {
                this.appOnlyCertificateThumbprintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
    public partial class DotNetHandlerType {
        
        private System.Xml.XmlElement configurationField;
        
        private string typeField;
        
        /// <remarks/>
        public System.Xml.XmlElement Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
    public partial class PnPPartnerPackConfigurationJobHandler : DotNetHandlerType {
        
        private PnPPartnerPackConfigurationJobHandlerJob[] jobsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Job", IsNullable=false)]
        public PnPPartnerPackConfigurationJobHandlerJob[] Jobs {
            get {
                return this.jobsField;
            }
            set {
                this.jobsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
    public partial class PnPPartnerPackConfigurationJobHandlerJob {
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
}
