//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration", IsNullable=false)]
public partial class PnPPartnerPackConfiguration {
    
    private PnPPartnerPackConfigurationCertificateSettings certificateSettingsField;
    
    private PnPPartnerPackConfigurationGeneralSettings generalSettingsField;
    
    private PnPPartnerPackConfigurationTenantSettings tenantSettingsField;
    
    private DotNetHandlerType provisioningRepositoryField;
    
    private PnPPartnerPackConfigurationProvisioningJobs provisioningJobsField;
    
    /// <remarks/>
    public PnPPartnerPackConfigurationCertificateSettings CertificateSettings {
        get {
            return this.certificateSettingsField;
        }
        set {
            this.certificateSettingsField = value;
        }
    }
    
    /// <remarks/>
    public PnPPartnerPackConfigurationGeneralSettings GeneralSettings {
        get {
            return this.generalSettingsField;
        }
        set {
            this.generalSettingsField = value;
        }
    }
    
    /// <remarks/>
    public PnPPartnerPackConfigurationTenantSettings TenantSettings {
        get {
            return this.tenantSettingsField;
        }
        set {
            this.tenantSettingsField = value;
        }
    }
    
    /// <remarks/>
    public DotNetHandlerType ProvisioningRepository {
        get {
            return this.provisioningRepositoryField;
        }
        set {
            this.provisioningRepositoryField = value;
        }
    }
    
    /// <remarks/>
    public PnPPartnerPackConfigurationProvisioningJobs ProvisioningJobs {
        get {
            return this.provisioningJobsField;
        }
        set {
            this.provisioningJobsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class PnPPartnerPackConfigurationCertificateSettings {
    
    private string storeNameField;
    
    private string storeLocationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string storeName {
        get {
            return this.storeNameField;
        }
        set {
            this.storeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string storeLocation {
        get {
            return this.storeLocationField;
        }
        set {
            this.storeLocationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class DotNetHandlerType {
    
    private System.Xml.XmlElement configurationField;
    
    private string nameField;
    
    private string typeField;
    
    /// <remarks/>
    public System.Xml.XmlElement Configuration {
        get {
            return this.configurationField;
        }
        set {
            this.configurationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class PnPPartnerPackConfigurationGeneralSettings {
    
    private System.Xml.XmlNode welcomeMessageField;
    
    private System.Xml.XmlNode footerMessageField;
    
    private string logoUrlField;
    
    private string titleField;
    
    private string defaultSiteTemplateField;
    
    /// <remarks/>
    public System.Xml.XmlNode WelcomeMessage {
        get {
            return this.welcomeMessageField;
        }
        set {
            this.welcomeMessageField = value;
        }
    }
    
    /// <remarks/>
    public System.Xml.XmlNode FooterMessage {
        get {
            return this.footerMessageField;
        }
        set {
            this.footerMessageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LogoUrl {
        get {
            return this.logoUrlField;
        }
        set {
            this.logoUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string defaultSiteTemplate {
        get {
            return this.defaultSiteTemplateField;
        }
        set {
            this.defaultSiteTemplateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class PnPPartnerPackConfigurationTenantSettings {
    
    private string tenantField;
    
    private string infrastructureSiteUrlField;
    
    private string appOnlyCertificateThumbprintField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string tenant {
        get {
            return this.tenantField;
        }
        set {
            this.tenantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string infrastructureSiteUrl {
        get {
            return this.infrastructureSiteUrlField;
        }
        set {
            this.infrastructureSiteUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string appOnlyCertificateThumbprint {
        get {
            return this.appOnlyCertificateThumbprintField;
        }
        set {
            this.appOnlyCertificateThumbprintField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class PnPPartnerPackConfigurationProvisioningJobs {
    
    private DotNetHandlerType[] jobHandlersField;
    
    private PnPPartnerPackConfigurationProvisioningJobsJobType[] jobTypesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("JobHandler", IsNullable=false)]
    public DotNetHandlerType[] JobHandlers {
        get {
            return this.jobHandlersField;
        }
        set {
            this.jobHandlersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("JobType", IsNullable=false)]
    public PnPPartnerPackConfigurationProvisioningJobsJobType[] JobTypes {
        get {
            return this.jobTypesField;
        }
        set {
            this.jobTypesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public partial class PnPPartnerPackConfigurationProvisioningJobsJobType {
    
    private string typeField;
    
    private string handlerField;
    
    private PnPPartnerPackConfigurationProvisioningJobsJobTypeExecutionModel executionModelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string handler {
        get {
            return this.handlerField;
        }
        set {
            this.handlerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PnPPartnerPackConfigurationProvisioningJobsJobTypeExecutionModel executionModel {
        get {
            return this.executionModelField;
        }
        set {
            this.executionModelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.dev.office.com/PnP/2015/10/PnPPartnerPackConfiguration")]
public enum PnPPartnerPackConfigurationProvisioningJobsJobTypeExecutionModel {
    
    /// <remarks/>
    Continous,
    
    /// <remarks/>
    Scheduled,
}
